Update abap_regex.ts
abaplint/transpiler pull request #734
Opened 2022-05-11 23:13 UTC by Dwivedirahul44

Update Punctuation class members

2022-05-12 14:47 UTC, Dwivedirahul44 commented
@larshp - please review and add suggestions or merge.

2022-05-13 05:28 UTC, larshp requested changes

2022-05-13 05:28 UTC, larshp commented on packages/runtime/src/builtin/to_mixed.ts
> -  min?: INumeric | number }): String {
please keep `min` in the code, I know its not used at the moment, but it is a parameter of the method

2022-05-13 16:46 UTC, Dwivedirahul44 commented on packages/runtime/src/abap_regex.ts
> +    ret = input.replace(/\[\[:punct:\]\]/g, "[\\.\\,\\-\\{\\}\\[\\]\\:\\!\\?\\(\\)\\;\\']");
update class members of punct

2022-05-13 16:47 UTC, Dwivedirahul44 commented on test/builtin/replace.ts
> +plain_text = |H-\\{\\}[...]ello, Wo:,rld!?.();'|.
update test case

2022-05-16 06:31 UTC, larshp commented
thanks 👍 

will be published in next version

2022-05-16 06:31 UTC, merged